services:
  backend:
    image: example-backend
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=redis
    restart: unless-stopped
  frontend:
    image: example-frontend
    ports:
      - 5000:5000
  redis:
    image: redis:latest
